stevemostovoy.me:
  image: stevemostovoy/stevemostovoy.me
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - "/var/www:/www"
    - "/etc/ssl/certs:/etc/ssl/certs"
    - "/etc/letsencrypt/archive/stevemostovoy.me:/ssl/archive/stevemostovoy.me"
    - "/etc/letsencrypt/live/stevemostovoy.me:/ssl/live/stevemostovoy.me"
